name: Build and Upload LLaMA Binary

on:
  workflow_dispatch:

permissions:
  contents: write  # Required to create and upload releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install build tools
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # 3. Clone llama.cpp and build with CURL support
      - name: Clone and Build llama.cpp
        run: |
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          mkdir build && cd build
          cmake .. -DLLAMA_CURL=ON
          cmake --build . --config Release -j$(nproc)

      # 4. Create GitHub Release & Upload Binary
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: llama-binary-v1
          name: "LLaMA Binary v1"
          draft: false
          prerelease: false
          files: |
            llama.cpp/build/bin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
