name: Build llama.cpp (Engine Only)

on:
  workflow_dispatch:  # Manually trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake wget unzip git-lfs libcurl4-openssl-dev

      # 3. Clone and build llama.cpp
      - name: Build llama.cpp
        run: |
          rm -rf llama.cpp
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          mkdir build && cd build
          cmake .. -DLLAMA_CURL=OFF
          cmake --build . --config Release -j$(nproc)

      # 4. Upload built llama.cpp as artifact
      - name: Upload llama.cpp
        uses: actions/upload-artifact@v4
        with:
          name: llama_cpp_engine
          path: llama.cpp/build
