name: Build llama.cpp with LLaMA 3.1 70B GGUF and Push to Backend

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout this repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake wget unzip git-lfs libcurl4-openssl-dev
          pip install huggingface_hub

      # 3. Build llama.cpp using CMake (disable CURL)
      - name: Build llama.cpp
        run: |
          rm -rf llama.cpp
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          mkdir build && cd build
          cmake .. -DLLAMA_CURL=OFF
          cmake --build . --config Release -j$(nproc)

      # 4. Download LLaMA 3.1 70B GGUF via huggingface-hub
      - name: Download LLaMA 3.1 70B GGUF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir -p llama.cpp/models
          huggingface-cli repo clone mav23/Llama-3.1-70B-Instruct-GGUF llama.cpp/models/llama3_70b --token "$HF_TOKEN"
          mv llama.cpp/models/llama3_70b/*.gguf llama.cpp/models/
          rm -rf llama.cpp/models/llama3_70b

      # 5. (Optional) Test the built binary locally
      - name: Test llama.cpp build
        run: |
          cd llama.cpp
          ./build/bin/main -m models/*.gguf -p "Hello from LLaMA 3.1 70B!"

      # 6. Push the build and model to your backend repo
      - name: Push to petgptfixed
        env:
          BACKEND_PAT: ${{ secrets.BACKEND_PAT }}
        run: |
          git clone https://x-access-token:${BACKEND_PAT}@github.com/besthathacker/petgptfixed.git backend_repo
          rsync -av --delete llama.cpp/ backend_repo/llama.cpp/
          cd backend_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add llama.cpp
          git commit -m "Update llama.cpp build + LLaMA 3.1 70B GGUF model" || echo "No changes to commit"
          git push
