name: Build and Upload LLaMA Binary

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libcurl4-openssl-dev zip

      # 3. Clone and build llama.cpp
      - name: Clone and Build llama.cpp
        run: |
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          mkdir build && cd build
          cmake .. -DLLAMA_CURL=ON
          cmake --build . --config Release -j$(nproc)

      # 4. Package the binary into a zip
      - name: Package Binary
        run: |
          cd llama.cpp/build/bin
          zip -r llama-binary.zip main

      # 5. Create a new release with the zip
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: llama-binary-${{ github.run_number }}
          name: "LLaMA Binary Build ${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            llama.cpp/build/bin/llama-binary.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
