name: Build llama.cpp with LLaMA 3 GGUF and Push to Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake wget unzip git-lfs

      # Fixed CMake build
      - name: Build llama.cpp
        run: |
          rm -rf llama.cpp
          git clone https://github.com/ggerganov/llama.cpp.git
          cd llama.cpp
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release -j $(nproc)

      - name: Download LLaMA 3 GGUF
        run: |
          mkdir -p llama.cpp/models
          cd llama.cpp/models
          echo "Downloading LLaMA 3 8B Q4_K_M GGUF model..."
          wget https://huggingface.co/TheBloke/LLaMA-3-8B-GGUF/resolve/main/llama-3-8b.Q4_K_M.gguf

      - name: Commit and Push llama.cpp + Model
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add llama.cpp
          git commit -m "Add CMake build of llama.cpp and LLaMA 3 GGUF model" || echo "No changes to commit"
          git push
